wandb_version: 1

GivenNames:
  value: Zhong Cheng
StudentID:
  value: '22212117'
Surname:
  value: Lau
batch_size:
  value: '8'
learning_rate:
  value: '0.001'
model:
  value: yolov8n.pt
num_epochs:
  value: '10'
train:
  value:
    agnostic_nms: 'true'
    amp: 'false'
    augment: 'false'
    auto_augment: randaugment
    batch: 4
    box: 9.419805890125598
    cache: 'false'
    close_mosaic: 15
    cls: 0.26695163526288257
    cos_lr: 'true'
    crop_fraction: 2
    data: C:\\Users\\Jonah\\OneDrive\\Desktop\\COMP3007-Machine-Perception-Assignment\\training_data\\task3\\Task
      3 Dataset LCD Digits\\data.yaml
    deterministic: 'false'
    dfl: 2.4416426596621337
    dnn: 'true'
    dynamic: 'false'
    epochs: 61
    erasing: 0.5015562778769911
    exist_ok: 'true'
    fliplr: 0.6851268057448348
    format: torchscript
    fraction: 2
    half: 'false'
    hsv_h: 0.01662294342017982
    hsv_s: 1.143712985514331
    hsv_v: 0.4723681324356475
    imgsz: 775
    int8: 'true'
    iou: 0.7736257225093436
    keras: 'true'
    kobj: 2
    lr0: 0.001111454831197353
    lrf: 0.012992914931562433
    mask_ratio: 6
    max_det: 447
    mode: train
    model: yolov8n.pt
    momentum: 1.6180225463676865
    mosaic: 2
    multi_scale: 'false'
    name: digit_LCD_classifier_model
    nbs: 99
    nms: 'true'
    optimize: 'false'
    optimizer: auto
    overlap_mask: 'false'
    patience: 118
    plots: 'true'
    pose: 15
    pretrained: 'false'
    profile: 'true'
    rect: 'true'
    resume: 'true'
    retina_masks: 'false'
    save: 'false'
    save_conf: 'false'
    save_crop: 'false'
    save_dir: runs\\detect\\digit_LCD_classifier_model
    save_frames: 'true'
    save_hybrid: 'false'
    save_json: 'true'
    save_period: -2
    save_txt: 'true'
    scale: 0.4956760562473084
    show: 'false'
    show_boxes: 'false'
    show_conf: 'false'
    show_labels: 'true'
    simplify: 'true'
    single_cls: 'true'
    split: val
    stream_buffer: 'false'
    task: detect
    tracker: botsort.yaml
    translate: 0.08417354517461981
    val: 'true'
    verbose: 'false'
    vid_stride: 2
    visualize: 'false'
    warmup_epochs: 3
    warmup_momentum: 1.3996046328967937
    weight_decay: 0.0003795162690658439
    workspace: 6
